#############################################################################
# Generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#  Dec 25, 2018 11:25:30 PM IST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family Calibri -size 12 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family {Copperplate Gothic Light} -size 14 -weight bold -slant italic -underline 0 -overstrike 0" \
    user \
    vTcl:font11
vTcl:font:add_font \
    "-family {Comic Sans MS} -size 12 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font12
vTcl:font:add_font \
    "-family {@Malgun Gothic} -size 12 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font13
vTcl:font:add_font \
    "-family {Segoe UI Black} -size 14 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 600x450+436+177
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TFrame -background #d9d9d9
    ttk::frame $top.tFr43 \
        -borderwidth 2 -relief groove -width 485 -height 145 
    vTcl:DefineAlias "$top.tFr43" "Notifier" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tFr43
    ttk::label $site_3_0.tLa44 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font11,object) -relief flat -anchor center \
        -text 00:00:00 -textvariable {} 
    vTcl:DefineAlias "$site_3_0.tLa44" "Clock" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa45 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font13,object) -relief flat -text 00:00 
    vTcl:DefineAlias "$site_3_0.tLa45" "StartTime_CE" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa46 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font12,object) -relief flat -anchor center \
        -text {current work} 
    vTcl:DefineAlias "$site_3_0.tLa46" "CurrentEvent" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa47 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font13,object) -relief flat -text 00:00 
    vTcl:DefineAlias "$site_3_0.tLa47" "EndTime_CE" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu48 \
        -takefocus {} -text Done 
    vTcl:DefineAlias "$site_3_0.tBu48" "DoneButton" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa49 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font13,object) -relief flat -text 11:10 
    vTcl:DefineAlias "$site_3_0.tLa49" "StartTime_NE" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa50 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font12,object) -relief flat -anchor center \
        -text {next work} 
    vTcl:DefineAlias "$site_3_0.tLa50" "NextEvent" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa51 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font13,object) -relief flat -text 11:11 
    vTcl:DefineAlias "$site_3_0.tLa51" "EndTime_NE" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tLa44 \
        -in $site_3_0 -x 180 -y 10 -width 126 -relwidth 0 -height 39 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa45 \
        -in $site_3_0 -x 30 -y 60 -width 66 -relwidth 0 -height 29 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa46 \
        -in $site_3_0 -x 110 -y 60 -width 156 -relwidth 0 -height 29 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa47 \
        -in $site_3_0 -x 280 -y 60 -width 66 -relwidth 0 -height 29 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu48 \
        -in $site_3_0 -x 390 -y 60 -width 76 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa49 \
        -in $site_3_0 -x 30 -y 100 -width 66 -relwidth 0 -height 29 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa50 \
        -in $site_3_0 -x 110 -y 100 -width 156 -relwidth 0 -height 29 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa51 \
        -in $site_3_0 -x 280 -y 100 -width 66 -relwidth 0 -height 29 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::style configure TFrame -background #d9d9d9
    ttk::frame $top.tFr52 \
        -borderwidth 2 -relief groove -width 485 -height 255 
    vTcl:DefineAlias "$top.tFr52" "Scheduler" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tFr52
    ttk::label $site_3_0.tLa53 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font9,object) -relief flat -anchor center \
        -text Events 
    vTcl:DefineAlias "$site_3_0.tLa53" "Header" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa57 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font10,object) -relief flat \
        -text {Start Time} 
    vTcl:DefineAlias "$site_3_0.tLa57" "StartTime_header" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa58 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font10,object) -relief flat -text {End Time} 
    vTcl:DefineAlias "$site_3_0.tLa58" "EndTime_header" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa59 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font10,object) -relief flat \
        -text {Event Name} 
    vTcl:DefineAlias "$site_3_0.tLa59" "Event_header" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tLa53 \
        -in $site_3_0 -x 190 -y 10 -width 107 -relwidth 0 -height 29 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa57 \
        -in $site_3_0 -x 40 -y 50 -width 76 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa58 \
        -in $site_3_0 -x 370 -y 50 -width 76 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa59 \
        -in $site_3_0 -x 200 -y 50 -width 97 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tFr43 \
        -in $top -x 60 -y 20 -width 485 -relwidth 0 -height 145 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tFr52 \
        -in $top -x 60 -y 180 -width 485 -relwidth 0 -height 255 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

